service: axsmap-api

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  signIn:
    handler: routes/auth.signIn
    events:
      - http:
          path: auth/sign-in
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpsProtocol: "certs"
    port: 8000